apiVersion: v1
kind: Service
metadata:
  creationTimestamp: 2017-06-09T06:45:53Z
  labels:
    run: my-nginx
  name: my-nginx
  namespace: default
  resourceVersion: "222961"
  selfLink: /api/v1/namespaces/default/services/my-nginx
  uid: 489286a7-4cdf-11e7-a325-42010a80022d
spec:
  clusterIP: 10.23.242.76
  ports:
  - nodePort: 32185
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    run: my-nginx
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - ip: 35.188.6.3
